### ISSUE TITLE
Mosekxx DLL not found

### ISSUE THREAD

**Issue by tiange997** [zjuidg/iStoryline#2]
Hi,

I am a researcher from Johannes Kepler University Linz. I was trying to implement your iStory Visualisation system in my research project. 

After the successful compilation of the programme, I found it was not possible to upload data and generate graphics. Please check the picture (or attachment) below for my issue in detail.

![71639509421_ pic](https://user-images.githubusercontent.com/61433528/146066202-f89712ea-084b-4e56-802a-71969a195f57.jpg)

One more to add, the dependency packages here are relatively obsolete, please update if possible.

Thanks a lot

**Comment by tangtan** [comment]
I agree the dependency packages are VERY obsolete. That's why I implement the JavaScript version iStoryline.js. The err seems to a missing package. How about contacting me using WeChat: tangtan1012.
